import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:outfitofTheDay/Services/home_daily_outfit_cache_service.dart';
import 'package:outfitofTheDay/Services/home_final_review_payload.dart';
import 'package:outfitofTheDay/domain/style_preferences/home_taste_cache_policy.dart';
import 'package:outfitofTheDay/domain/style_preferences/style_preference_taste.dart';
import 'package:outfitofTheDay/domain/style_preferences/user_style_preferences.dart';
import 'package:outfitofTheDay/domain/wardrobe_v2/flexible_candidate_matrix_v2.dart';
import 'package:outfitofTheDay/domain/wardrobe_v2/flexible_outfit_result_v2.dart';
import 'package:outfitofTheDay/domain/wardrobe_v2/outfit_composition_v2.dart';
import 'package:outfitofTheDay/domain/wardrobe_v2/wardrobe_item_v2.dart';
import 'package:outfitofTheDay/utils/home_user_facing_reason.dart';

void main() {
  group('Home taste fingerprint', () {
    test('same sets in different order produce the same fingerprint', () {
      final a = UserStylePreferences.fromMap({
        'favoriteColors': ['Modrá', 'Červená'],
        'preferredStyles': ['Casual', 'Elegantný'],
        'favoriteBrands': ['Nike', 'Zara'],
      });
      final b = UserStylePreferences.fromMap({
        'favoriteColors': ['Červená', 'Modrá'],
        'preferredStyles': ['Elegantný', 'Casual'],
        'favoriteBrands': ['Zara', 'Nike'],
      });
      expect(a.homeTasteFingerprint, b.homeTasteFingerprint);
    });

    test('actual taste changes produce a different fingerprint', () {
      final base = UserStylePreferences.fromMap({
        'favoriteColors': ['Modrá'],
        'avoidedColors': ['Červená'],
        'preferredStyles': ['Casual'],
        'favoriteBrands': ['Nike'],
      });
      expect(
        UserStylePreferences.fromMap({
          'favoriteColors': ['Zelená'],
        }).homeTasteFingerprint,
        isNot(base.homeTasteFingerprint),
      );
      expect(
        UserStylePreferences.fromMap({
          'avoidedColors': ['Čierna'],
        }).homeTasteFingerprint,
        isNot(base.homeTasteFingerprint),
      );
      expect(
        UserStylePreferences.fromMap({
          'preferredStyles': ['Business'],
        }).homeTasteFingerprint,
        isNot(base.homeTasteFingerprint),
      );
      expect(
        UserStylePreferences.fromMap({
          'favoriteBrands': ['Adidas'],
        }).homeTasteFingerprint,
        isNot(base.homeTasteFingerprint),
      );
    });

    test('size-only changes do not affect the Home taste fingerprint', () {
      final taste = {
        'favoriteColors': ['Modrá'],
        'preferredStyles': ['Casual'],
      };
      final withSizes = UserStylePreferences.fromMap({
        ...taste,
        'topSize': 'M',
        'shoeSize': '42',
        'pantsSize': '32',
      });
      final withoutSizes = UserStylePreferences.fromMap(taste);
      expect(withSizes.homeTasteFingerprint, withoutSizes.homeTasteFingerprint);
    });

    test('missing and empty preferences share a stable empty fingerprint', () {
      expect(
        UserStylePreferences.fromMap(null).homeTasteFingerprint,
        UserStylePreferences.emptyHomeTasteFingerprint,
      );
      expect(
        UserStylePreferences.fromMap({
          'favoriteColors': <String>[],
          'shoeSize': '42',
        }).homeTasteFingerprint,
        UserStylePreferences.emptyHomeTasteFingerprint,
      );
    });
  });

  group('Home cache invalidation policy', () {
    const current = 'v1:c=blue|a=|s=casual|b=';

    test('compatible auto-generated cache may be reused', () {
      expect(
        HomeTasteCachePolicy.isAutoGeneratedTasteIncompatible(
          userPinned: false,
          cachedFingerprint: current,
          currentFingerprint: current,
        ),
        isFalse,
      );
    });

    test('changed preferences make auto-generated cache incompatible', () {
      expect(
        HomeTasteCachePolicy.isAutoGeneratedTasteIncompatible(
          userPinned: false,
          cachedFingerprint: current,
          currentFingerprint: 'v1:c=red|a=|s=casual|b=',
        ),
        isTrue,
      );
    });

    test('legacy auto-generated docs missing fingerprint are stale', () {
      expect(
        HomeTasteCachePolicy.isAutoGeneratedTasteIncompatible(
          userPinned: false,
          cachedFingerprint: '',
          currentFingerprint: UserStylePreferences.emptyHomeTasteFingerprint,
        ),
        isTrue,
      );
    });

    test('pinned or manual outfits are not discarded on preference change', () {
      expect(
        HomeTasteCachePolicy.isUserPinned(
          userModified: true,
          persistSource: 'ai_generated',
        ),
        isTrue,
      );
      expect(
        HomeTasteCachePolicy.isUserPinned(
          userModified: false,
          persistSource: 'manual_new_outfit',
        ),
        isTrue,
      );
      expect(
        HomeTasteCachePolicy.isAutoGeneratedTasteIncompatible(
          userPinned: true,
          cachedFingerprint: '',
          currentFingerprint: current,
        ),
        isFalse,
      );
    });

    test('persisted Home cache documents round-trip the fingerprint', () {
      final doc = HomeDailyOutfitCacheService.parseDocument('2026-08-17', {
        'itemIds': ['a', 'b', 'c'],
        'items': [
          {'wardrobeItemId': 'a'},
          {'wardrobeItemId': 'b'},
          {'wardrobeItemId': 'c'},
        ],
        'weatherSignature': '20|0|0|let',
        'wardrobeSignature': '3:a,b,c',
        'stylePreferenceFingerprint': current,
        'source': 'ai_generated',
        'userModified': false,
      });
      expect(doc, isNotNull);
      expect(doc!.stylePreferenceFingerprint, current);
    });
  });

  group('Subordinate taste scoring', () {
    test('favorite color is a soft tie-break among equally suitable outfits', () {
      final blue = _outfit(color: 'blue');
      final gray = _outfit(color: 'gray');
      final taste = StylePreferenceTaste.fromPreferences(
        UserStylePreferences.fromMap({'favoriteColors': ['Modrá']}),
      );
      final context = V2CandidateMatrixContext(styleTaste: taste);
      expect(
        V2FlexibleOutfitScorer.score(blue, context)['styleTaste'],
        StylePreferenceTasteScorer.favoriteColorBonus,
      );
      expect(V2FlexibleOutfitScorer.score(gray, context)['styleTaste'], 0);
      expect(
        _total(blue, context),
        greaterThan(_total(gray, context)),
      );
    });

    test('avoided color is a penalty, not a hard exclusion', () {
      final red = _outfit(color: 'red');
      final navy = _outfit(color: 'navy');
      final taste = StylePreferenceTaste.fromPreferences(
        UserStylePreferences.fromMap({'avoidedColors': ['Červená']}),
      );
      final context = V2CandidateMatrixContext(styleTaste: taste);
      expect(
        V2FlexibleOutfitScorer.score(red, context)['styleTaste'],
        StylePreferenceTasteScorer.avoidedColorPenalty,
      );
      expect(
        V2FlexibleOutfitScorer.score(navy, context)['styleTaste'],
        0,
      );
      expect(_total(navy, context), greaterThan(_total(red, context)));
    });

    test('suitability still dominates an avoided-color weather-safe outfit', () {
      final safeRedJacket = _outfit(color: 'red', weatherComplete: true);
      final favoriteNoProtection = _outfit(
        color: 'blue',
        weatherComplete: false,
      );
      final taste = StylePreferenceTaste.fromPreferences(
        UserStylePreferences.fromMap({
          'favoriteColors': ['Modrá'],
          'avoidedColors': ['Červená'],
        }),
      );
      final rainy = V2CandidateMatrixContext(
        isRainy: true,
        weatherProtectionRequired: true,
        styleTaste: taste,
      );
      expect(
        V2FlexibleOutfitScorer.score(safeRedJacket, rainy)['weather'],
        2,
      );
      expect(
        V2FlexibleOutfitScorer.score(favoriteNoProtection, rainy)['weather'],
        -8,
      );
      expect(
        _total(safeRedJacket, rainy) - _total(favoriteNoProtection, rainy),
        greaterThan(StylePreferenceTasteScorer.maxAbsScore),
      );
    });

    test('preferred style overlap is a soft positive on valid outfits', () {
      final casual = _outfit(color: 'gray', styles: const ['Casual']);
      final plain = _outfit(color: 'gray');
      final taste = StylePreferenceTaste.fromPreferences(
        UserStylePreferences.fromMap({'preferredStyles': ['Casual']}),
      );
      final context = V2CandidateMatrixContext(styleTaste: taste);
      expect(
        V2FlexibleOutfitScorer.score(casual, context)['styleTaste'],
        StylePreferenceTasteScorer.preferredStyleBonus,
      );
      expect(V2FlexibleOutfitScorer.score(plain, context)['styleTaste'], 0);
    });

    test('favorite brand is a weak positive only when brand metadata exists', () {
      final branded = _outfit(color: 'gray', brand: 'Nike');
      final unbranded = _outfit(color: 'gray');
      final taste = StylePreferenceTaste.fromPreferences(
        UserStylePreferences.fromMap({'favoriteBrands': ['Nike']}),
      );
      final context = V2CandidateMatrixContext(styleTaste: taste);
      expect(
        V2FlexibleOutfitScorer.score(branded, context)['styleTaste'],
        StylePreferenceTasteScorer.favoriteBrandBonus,
      );
      expect(V2FlexibleOutfitScorer.score(unbranded, context)['styleTaste'], 0);
    });

    test('missing style or brand metadata is not penalized', () {
      final plain = _outfit(color: 'gray');
      final taste = StylePreferenceTaste.fromPreferences(
        UserStylePreferences.fromMap({
          'preferredStyles': ['Casual'],
          'favoriteBrands': ['Nike'],
        }),
      );
      expect(
        V2FlexibleOutfitScorer.score(
          plain,
          V2CandidateMatrixContext(styleTaste: taste),
        )['styleTaste'],
        0,
      );
    });
  });

  group('Home final review preference envelope', () {
    test('compact payload stays bounded and omits sizes', () {
      final prefs = UserStylePreferences.fromMap({
        'favoriteColors': ['Modrá'],
        'avoidedColors': ['Červená'],
        'preferredStyles': ['Casual'],
        'favoriteBrands': ['Nike'],
        'shoeSize': '42',
        'email': 'hidden@example.com',
      }).toStylistPayload();
      expect(prefs, isNotNull);
      expect(prefs!.containsKey('shoeSize'), isFalse);
      expect(prefs.containsKey('email'), isFalse);
      final envelope = <String, dynamic>{
        'weatherContext': {'tempC': 20, 'isRainy': false},
        'candidates': HomeFinalReviewPayload.fromCandidates([_candidate()]),
        'userStylePreferences': prefs,
      };
      expect(
        HomeFinalReviewPayload.isCompact(
          (envelope['candidates'] as List).first as Map<String, dynamic>,
        ),
        isTrue,
      );
      expect(HomeFinalReviewPayload.utf8ByteLength(envelope), lessThan(3500));
    });

    test('empty prefs are omitted from the envelope', () {
      expect(UserStylePreferences.empty.toStylistPayload(), isNull);
    });
  });

  group('Explain and wiring', () {
    test('preference copy stays human and is not an internal label', () {
      final hint = StylePreferenceExplain.naturalHint(
        taste: StylePreferenceTaste.fromPreferences(
          UserStylePreferences.fromMap({'favoriteColors': ['Modrá']}),
        ),
        outfit: _outfit(color: 'blue'),
        tasteScore: StylePreferenceTasteScorer.favoriteColorBonus,
      );
      expect(hint, isNotNull);
      expect(HomeUserFacingReason.isInternal(hint), isFalse);
      expect(hint!.contains('favoriteColors'), isFalse);
      expect(hint.contains('_'), isFalse);
    });

    test('Home consumes the authoritative reader; Calendar and Trip do not', () {
      final home = File('lib/screens/home_screen.dart').readAsStringSync();
      expect(home.contains('UserStylePreferencesReader'), isTrue);
      expect(home.contains('stylePreferenceFingerprint'), isTrue);
      expect(home.contains('StylePreferencesRuntime'), isTrue);
      expect(home.contains('tomorrow_deferred_until_zajtra'), isTrue);
      expect(home.contains('ensure_today_only'), isTrue);
      const protected = [
        'lib/Services/calendar_outfit_service.dart',
        'lib/screens/trip_planner_screen.dart',
        'lib/Services/trip_packing_service.dart',
      ];
      for (final path in protected) {
        final src = File(path).readAsStringSync();
        expect(src.contains('UserStylePreferencesReader'), isFalse);
        expect(src.contains('stylePreferenceFingerprint'), isFalse);
      }
    });
  });
}

double _total(V2FlexibleOutfitResult outfit, V2CandidateMatrixContext context) {
  return V2FlexibleOutfitScorer.score(outfit, context).values.fold(0, (a, b) => a + b);
}

V2FlexibleCandidate _candidate() {
  final outfit = _outfit(color: 'navy');
  return V2FlexibleCandidate(
    candidateId: 'v2_1',
    outfit: outfit,
    score: 12,
    scoreBreakdown: const {'core': 4, 'weather': 2},
  );
}

V2FlexibleOutfitResult _outfit({
  required String color,
  bool weatherComplete = true,
  List<String> styles = const [],
  String brand = '',
}) {
  WardrobeItemV2 piece(
    String id,
    String type,
    String family,
    List<String> slots,
    String layer,
  ) {
    return WardrobeItemV2(
      canonicalType: type,
      canonicalFamily: family,
      bodySlots: slots,
      layerPosition: layer,
      colorProfile: ColorProfileV2(
        primary: SemanticColorV2(family: color),
      ),
      formality: 4,
      styles: styles,
      occasionFit: const ['everyday'],
      seasons: const ['summer'],
      warmth: 3,
      attributes: const {},
      fieldSources: const {'canonicalType': 'visual_ai'},
      fieldConfidence: const {'canonicalType': 0.9},
      userOverrideFields: const [],
    );
  }

  V2FlexibleOutfitItem wrap(
    String id,
    WardrobeItemV2 item,
    String group,
  ) {
    return V2FlexibleOutfitItem(
      itemId: id,
      item: item,
      compositionRole: CompositionRoleV2.core,
      compositionGroup: group,
      requiredness: 'required',
      selectionReason: 'core',
      display: brand.isEmpty ? const {} : {'brand': brand},
    );
  }

  return V2FlexibleOutfitResult(
    template: OutfitTemplateV2.separates,
    items: [
      wrap(
        'top',
        piece('top', 't_shirt', 'top', const ['upper_body'], 'base'),
        'upper_body_core',
      ),
      wrap(
        'bottom',
        piece('bottom', 'jeans', 'bottom', const ['lower_body'], 'outer'),
        'lower_body_core',
      ),
      wrap(
        'shoes',
        piece('shoes', 'sneakers', 'footwear', const ['feet'], 'not_applicable'),
        'footwear',
      ),
    ],
    completeness: OutfitCompletenessV2(
      coreComplete: true,
      weatherComplete: weatherComplete,
      dressCodeComplete: true,
      functionalComplete: true,
      enhanced: false,
      gaps: const [],
    ),
  );
}
