import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:outfitofTheDay/Services/stylist_chat_service.dart';
import 'package:outfitofTheDay/Services/user_style_preferences_reader.dart';
import 'package:outfitofTheDay/domain/style_preferences/home_taste_cache_policy.dart';
import 'package:outfitofTheDay/domain/style_preferences/style_preference_taste.dart';
import 'package:outfitofTheDay/domain/style_preferences/style_preferences_runtime.dart';
import 'package:outfitofTheDay/domain/style_preferences/user_style_preferences.dart';
import 'package:outfitofTheDay/domain/wardrobe_v2/flexible_candidate_matrix_v2.dart';
import 'package:outfitofTheDay/domain/wardrobe_v2/flexible_outfit_result_v2.dart';
import 'package:outfitofTheDay/domain/wardrobe_v2/outfit_composition_v2.dart';
import 'package:outfitofTheDay/domain/wardrobe_v2/wardrobe_item_v2.dart';

void main() {
  tearDown(() => StylePreferencesRuntime.debugOverrideEnabled(null));

  final savedA = UserStylePreferences.fromMap({
    'favoriteColors': ['Modrá'],
    'preferredStyles': ['Casual'],
    'favoriteBrands': ['Nike'],
  });
  final savedB = UserStylePreferences.fromMap({
    'favoriteColors': ['Červená'],
    'avoidedColors': ['Zelená'],
    'preferredStyles': ['Business'],
  });

  test('compile-time default disables runtime consumption', () {
    expect(StylePreferencesRuntime.enabledDefine, isFalse);
  });

  group('Flag off — Home', () {
    test('saved taste scores as empty and omits explanation and final-review payload', () {
      StylePreferencesRuntime.debugOverrideEnabled(false);
      final taste = StylePreferencesRuntime.effectiveTaste(savedA);
      expect(taste.isEmpty, isTrue);
      expect(taste, StylePreferenceTaste.empty);
      final outfit = _outfit(color: 'blue', styles: const ['casual'], brand: 'Nike');
      expect(
        StylePreferenceTasteScorer.score(outfit: outfit, taste: taste),
        0,
      );
      expect(
        StylePreferenceExplain.naturalHint(
          taste: taste,
          outfit: outfit,
          tasteScore: 0.8,
        ),
        isNull,
      );
      expect(StylePreferencesRuntime.stylistPayload(savedA), isNull);
      expect(
        V2FlexibleOutfitScorer.score(
          outfit,
          V2CandidateMatrixContext(
            styleTaste: StylePreferencesRuntime.effectiveTaste(savedA),
          ),
        )['styleTaste'],
        0,
      );
    });
  });

  group('Flag off — fingerprint', () {
    test('different saved preferences share the disabled runtime fingerprint', () {
      StylePreferencesRuntime.debugOverrideEnabled(false);
      expect(
        StylePreferencesRuntime.consumptionFingerprint(savedA),
        StylePreferencesRuntime.disabledConsumptionFingerprint,
      );
      expect(
        StylePreferencesRuntime.consumptionFingerprint(savedA),
        StylePreferencesRuntime.consumptionFingerprint(savedB),
      );
      expect(
        savedA.homeTasteFingerprint,
        isNot(savedB.homeTasteFingerprint),
      );
    });
  });

  group('Toggle off invalidates auto cache', () {
    test('previous taste-enabled auto cache is incompatible once disabled', () {
      StylePreferencesRuntime.debugOverrideEnabled(true);
      final enabledFp = StylePreferencesRuntime.consumptionFingerprint(savedA);
      StylePreferencesRuntime.debugOverrideEnabled(false);
      final disabledFp = StylePreferencesRuntime.consumptionFingerprint(savedA);
      expect(enabledFp, startsWith('tasteRuntime=on:'));
      expect(disabledFp, StylePreferencesRuntime.disabledConsumptionFingerprint);
      expect(
        HomeTasteCachePolicy.isAutoGeneratedTasteIncompatible(
          userPinned: false,
          cachedFingerprint: enabledFp,
          currentFingerprint: disabledFp,
        ),
        isTrue,
      );
    });

    test('pinned or manual outfits are not discarded on runtime flag change', () {
      StylePreferencesRuntime.debugOverrideEnabled(true);
      final enabledFp = StylePreferencesRuntime.consumptionFingerprint(savedA);
      StylePreferencesRuntime.debugOverrideEnabled(false);
      expect(
        HomeTasteCachePolicy.isAutoGeneratedTasteIncompatible(
          userPinned: true,
          cachedFingerprint: enabledFp,
          currentFingerprint: StylePreferencesRuntime.consumptionFingerprint(
            savedA,
          ),
        ),
        isFalse,
      );
      expect(
        HomeTasteCachePolicy.isUserPinned(
          userModified: true,
          persistSource: 'ai_generated',
        ),
        isTrue,
      );
    });
  });

  group('Toggle on again', () {
    test('saved preferences are consumed again without rewriting the store', () async {
      final reader = _CountingReader(savedA);
      StylePreferencesRuntime.debugOverrideEnabled(false);
      expect(
        await StylistChatService.resolveStylePreferencesPayload(reader, 'uid-1'),
        isNull,
      );
      expect(reader.loads, 0);

      StylePreferencesRuntime.debugOverrideEnabled(true);
      final payload = await StylistChatService.resolveStylePreferencesPayload(
        reader,
        'uid-1',
      );
      expect(payload, isNotNull);
      expect(payload!['favoriteColors'], ['blue']);
      expect(reader.loads, 1);
      expect(reader.writes, 0);
      expect(reader.prefs.favoriteColors, ['Modrá']);
    });
  });

  group('Home wiring', () {
    test('Home uses the shared runtime flag for taste, payload, and fingerprint', () {
      final home = File('lib/screens/home_screen.dart').readAsStringSync();
      expect(home.contains('StylePreferencesRuntime.effectiveTaste'), isTrue);
      expect(home.contains('StylePreferencesRuntime.stylistPayload'), isTrue);
      expect(
        home.contains('StylePreferencesRuntime.consumptionFingerprint'),
        isTrue,
      );
      expect(
        File('lib/Services/stylist_chat_service.dart').readAsStringSync().contains(
          'StylePreferencesRuntime.enabled',
        ),
        isTrue,
      );
    });
  });
}

class _CountingReader extends UserStylePreferencesReader {
  _CountingReader(this.prefs);

  final UserStylePreferences prefs;
  int loads = 0;
  int writes = 0;

  @override
  Future<UserStylePreferences> loadForUid(String? uid) async {
    loads++;
    return prefs;
  }
}

V2FlexibleOutfitResult _outfit({
  required String color,
  List<String> styles = const [],
  String brand = '',
}) {
  WardrobeItemV2 piece(
    String id,
    String type,
    String family,
    List<String> slots,
    String layer,
  ) {
    return WardrobeItemV2(
      canonicalType: type,
      canonicalFamily: family,
      bodySlots: slots,
      layerPosition: layer,
      colorProfile: ColorProfileV2(
        primary: SemanticColorV2(family: color),
      ),
      formality: 4,
      styles: styles,
      occasionFit: const ['everyday'],
      seasons: const ['summer'],
      warmth: 3,
      attributes: const {},
      fieldSources: const {'canonicalType': 'visual_ai'},
      fieldConfidence: const {'canonicalType': 0.9},
      userOverrideFields: const [],
    );
  }

  V2FlexibleOutfitItem wrap(String id, WardrobeItemV2 item, String group) {
    return V2FlexibleOutfitItem(
      itemId: id,
      item: item,
      compositionRole: CompositionRoleV2.core,
      compositionGroup: group,
      requiredness: 'required',
      selectionReason: 'core',
      display: brand.isEmpty ? const {} : {'brand': brand},
    );
  }

  return V2FlexibleOutfitResult(
    template: OutfitTemplateV2.separates,
    items: [
      wrap(
        'top',
        piece('top', 't_shirt', 'top', const ['upper_body'], 'base'),
        'upper_body_core',
      ),
      wrap(
        'bottom',
        piece('bottom', 'jeans', 'bottom', const ['lower_body'], 'outer'),
        'lower_body_core',
      ),
      wrap(
        'shoes',
        piece('shoes', 'sneakers', 'footwear', const ['feet'], 'not_applicable'),
        'footwear',
      ),
    ],
    completeness: const OutfitCompletenessV2(
      coreComplete: true,
      weatherComplete: true,
      dressCodeComplete: true,
      functionalComplete: true,
      enhanced: false,
      gaps: [],
    ),
  );
}
