"use strict";

const BACKEND_PROVIDER_STATUSES = Object.freeze([
  "not_started",
  "parity_ready",
]);

const BACKEND_ORCHESTRATION_STATUSES = Object.freeze([
  "not_started",
  "orchestration_ready",
]);

const provider = (definition) => Object.freeze({
  kbDependency: false,
  flutterDependency: false,
  orchestratorDependency: false,
  mapperDependency: false,
  finalResolverDependency: false,
  nodeSource: null,
  ...definition,
  upstream: Object.freeze([...definition.upstream]),
  downstream: Object.freeze([...definition.downstream]),
  blockers: Object.freeze([...(definition.blockers || [])]),
});

const orchestrationStage = (definition) => Object.freeze({
  kind: "orchestration_stage",
  nodeSource: null,
  ...definition,
  upstream: Object.freeze([...definition.upstream]),
  downstream: Object.freeze([...definition.downstream]),
  blockers: Object.freeze([...(definition.blockers || [])]),
});

const artifact = (definition) => Object.freeze({
  kind: "kb_artifact",
  nodeLoader: null,
  ...definition,
  consumers: Object.freeze([...(definition.consumers || [])]),
  blockers: Object.freeze([...(definition.blockers || [])]),
});

/**
 * Audited qualification DAG as of M11.1 Phase 5.3B-1B.
 *
 * This is test/audit metadata only. It is deliberately not imported by the
 * production Vision endpoint and does not execute qualification logic.
 */
const BACKEND_PROVIDER_GRAPH = Object.freeze([
  provider({
    id: "VisionFramingAttestor",
    dartSource: "lib/domain/wardrobe_profile/vision_framing_attestation.dart",
    nodeSource: "functions/vision_framing_attestor.js",
    input: "parser inputAssessment + subjectAssessment + quality + framingAttestations",
    output: "VisionFramingAttestationReport",
    upstream: [],
    downstream: [
      "VisionPropertyApplicabilityQualifier",
      "VisionNegativeClaimCorroborator",
      "VisionIdentityQualification",
      "VisionFamilyIdentityResolver",
    ],
    orchestratorDependency: true,
    status: "parity_ready",
    portableNow: true,
    blockers: [],
  }),
  provider({
    id: "VisionPropertyApplicabilityQualifier",
    dartSource: "lib/domain/wardrobe_profile/vision_subject_safety.dart",
    nodeSource:
      "functions/vision_property_applicability_qualifier.js",
    input: "raw observation bundle + framing-qualified subject",
    output: "VisionApplicabilityReport with qualified bundle",
    upstream: ["VisionFramingAttestor"],
    downstream: ["VisionVisibilityTrustQualifier"],
    orchestratorDependency: true,
    status: "parity_ready",
    portableNow: true,
    blockers: [],
  }),
  provider({
    id: "VisionVisibilityTrustQualifier",
    dartSource: "lib/domain/wardrobe_profile/vision_visibility_trust.dart",
    nodeSource: "functions/vision_visibility_trust_qualifier.js",
    input: "applicability-qualified bundle + input assessment + multi-view context",
    output: "VisionVisibilityTrustReport with qualified bundle",
    upstream: ["VisionPropertyApplicabilityQualifier"],
    downstream: ["VisionNegativeClaimCorroborator"],
    orchestratorDependency: true,
    status: "parity_ready",
    portableNow: true,
    blockers: [],
  }),
  provider({
    id: "VisionNegativeClaimCorroborator",
    dartSource: "lib/domain/wardrobe_profile/vision_framing_attestation.dart",
    nodeSource: "functions/vision_negative_claim_corroborator.js",
    input: "visibility-qualified bundle + subject/framing + multi-view conflict context",
    output: "NegativeClaimCorroborationReport with qualified bundle",
    upstream: [
      "VisionFramingAttestor",
      "VisionVisibilityTrustQualifier",
    ],
    downstream: ["ObservationAbsenceQualifier"],
    orchestratorDependency: true,
    status: "parity_ready",
    portableNow: true,
    blockers: [],
  }),
  provider({
    id: "ObservationAbsenceQualifier",
    dartSource: "lib/domain/wardrobe_profile/observation_absence_qualifier.dart",
    nodeSource: "functions/observation_absence_qualifier.js",
    input: "corroboration-qualified observation bundles",
    output: "ObservationAbsenceQualificationReport with merged qualified bundle",
    upstream: ["VisionNegativeClaimCorroborator"],
    downstream: ["VisionObservationEvidenceProvider"],
    orchestratorDependency: true,
    status: "parity_ready",
    portableNow: true,
    blockers: [],
  }),
  provider({
    id: "VisionObservationEvidenceProvider",
    dartSource: "lib/domain/wardrobe_profile/vision_observation_evidence_provider.dart",
    nodeSource: "functions/vision_observation_evidence_provider.js",
    input: "absence-qualified ClothingObservationBundle",
    output: "ordered List<ProfileEvidence> visual observations",
    upstream: ["ObservationAbsenceQualifier"],
    downstream: [
      "CanonicalObservationConsistencyValidator",
      "WardrobeCapabilityInferenceProvider",
      "WardrobeKnowledgeBasePriorProvider",
      "WardrobeProfileResolver",
      "QualifiedVisionPersistenceMapper",
    ],
    status: "parity_ready",
    portableNow: true,
    blockers: [],
  }),
  provider({
    id: "CanonicalObservationConsistencyValidator",
    dartSource: "lib/domain/wardrobe_profile/canonical_observation_consistency_validator.dart",
    nodeSource:
      "functions/canonical_observation_consistency_validator.js",
    input: "raw identity evidence + observation evidence",
    output: "CanonicalConsistencyReport",
    upstream: ["VisionObservationEvidenceProvider"],
    downstream: ["VisionIdentityQualification"],
    status: "parity_ready",
    portableNow: true,
    blockers: [],
  }),
  provider({
    id: "VisionIdentityQualification",
    dartSource: "lib/domain/wardrobe_profile/vision_v2_shadow_analysis.dart",
    nodeSource: "functions/vision_identity_qualifier.js",
    input: "identity candidates + consistency + declared supports + framing/multi-view validity",
    output: "qualified identity evidence + VisionIdentityQualificationReport",
    upstream: [
      "VisionFramingAttestor",
      "CanonicalObservationConsistencyValidator",
    ],
    downstream: [
      "VisionFamilyIdentityResolver",
      "WardrobeKnowledgeBasePriorProvider",
      "WardrobeProfileResolver",
      "QualifiedVisionPersistenceMapper",
    ],
    orchestratorDependency: true,
    status: "parity_ready",
    portableNow: true,
    blockers: [],
  }),
  provider({
    id: "VisionFamilyIdentityResolver",
    dartSource: "lib/domain/wardrobe_profile/vision_family_identity.dart",
    nodeSource: "functions/vision_family_identity_resolver.js",
    input: "identity candidates + raw observations + qualified subtype + framing/subject validity",
    output: "VisionFamilyIdentityReport",
    upstream: [
      "VisionFramingAttestor",
      "VisionIdentityQualification",
    ],
    downstream: ["QualifiedVisionPersistenceMapper"],
    status: "parity_ready",
    portableNow: true,
    blockers: [],
  }),
  provider({
    id: "WardrobeCapabilityInferenceProvider",
    dartSource: "lib/domain/wardrobe_profile/wardrobe_capability_inference_provider.dart",
    nodeSource: "functions/wardrobe_capability_inference_provider.js",
    input: "observation evidence + analysisId + observedAt",
    output: "ordered capability ProfileEvidence",
    upstream: ["VisionObservationEvidenceProvider"],
    downstream: [
      "WardrobeKnowledgeBasePriorProvider",
      "WardrobeProfileResolver",
      "QualifiedVisionPersistenceMapper",
    ],
    status: "parity_ready",
    portableNow: true,
    blockers: [],
  }),
  provider({
    id: "WardrobeKnowledgeBasePriorProvider",
    dartSource: "lib/domain/wardrobe_profile/wardrobe_knowledge_base_prior_provider.dart",
    nodeSource: "functions/wardrobe_knowledge_base_prior_provider.js",
    input: "empty vision document + observation/identity/capability evidence",
    output: "defaulted knowledge-base ProfileEvidence",
    upstream: [
      "VisionObservationEvidenceProvider",
      "VisionIdentityQualification",
      "WardrobeCapabilityInferenceProvider",
    ],
    downstream: ["WardrobeProfileResolver"],
    kbDependency: true,
    status: "parity_ready",
    portableNow: true,
    blockers: [],
    oracleReady: true,
    oracleManifest:
      "test/fixtures/backend_qualification/backend_wardrobe_kb_prior_oracle_manifest.json",
    kbArtifactId: "ClothingKnowledgeBasePriorArtifact",
  }),
  provider({
    id: "WardrobeProfileResolver",
    dartSource: "lib/domain/wardrobe_profile/wardrobe_profile_resolver.dart",
    nodeSource: "functions/wardrobe_profile_resolver.js",
    input: "itemId + observation/identity/capability/kb prior evidence",
    output: "ResolvedWardrobeItemProfile",
    upstream: [
      "VisionObservationEvidenceProvider",
      "VisionIdentityQualification",
      "WardrobeCapabilityInferenceProvider",
      "WardrobeKnowledgeBasePriorProvider",
    ],
    downstream: ["QualifiedVisionPersistenceMapper"],
    finalResolverDependency: true,
    status: "parity_ready",
    portableNow: true,
    blockers: [],
    oracleReady: true,
    oracleManifest:
      "test/fixtures/backend_qualification/backend_wardrobe_profile_resolver_oracle_manifest.json",
  }),
  provider({
    id: "QualifiedVisionPersistenceMapper",
    dartSource: "lib/domain/wardrobe_profile/qualified_vision_persistence_mapper.dart",
    nodeSource: "functions/qualified_vision_persistence_mapper.js",
    input: "qualified VisionV2ShadowAnalysis + persistence context",
    output: "WardrobeProfilePersistenceMappingResult",
    upstream: [
      "VisionObservationEvidenceProvider",
      "VisionIdentityQualification",
      "VisionFamilyIdentityResolver",
      "WardrobeCapabilityInferenceProvider",
      "WardrobeProfileResolver",
    ],
    downstream: [],
    mapperDependency: true,
    status: "parity_ready",
    portableNow: true,
    blockers: [],
    productionBlockers: [
      "production_write_boundary",
      "migration_required",
      "production_export_pending",
    ],
    oracleReady: true,
    oracleManifest:
      "test/fixtures/backend_qualification/backend_qualified_vision_persistence_mapper_oracle_manifest.json",
    terminal: true,
  }),
]);

/**
 * Orchestration stages are not counted in provider parity-ready totals.
 */
const BACKEND_ORCHESTRATION_GRAPH = Object.freeze([
  orchestrationStage({
    id: "PrepareVisionIdentityQualificationInput",
    dartSource: "lib/domain/wardrobe_profile/vision_v2_shadow_analysis.dart",
    nodeSource: "functions/prepare_vision_identity_qualification_input.js",
    input: "trusted parser responses + parity-ready observationEvidence + framing/multi-view context",
    output: "BackendIdentityQualificationInput/v1",
    upstream: [
      "VisionFramingAttestor",
      "VisionObservationEvidenceProvider",
      "CanonicalObservationConsistencyValidator",
    ],
    downstream: ["VisionIdentityQualification"],
    status: "orchestration_ready",
    portableNow: true,
    blockers: [],
  }),
  orchestrationStage({
    id: "PrepareVisionFamilyIdentityInput",
    dartSource: "lib/domain/wardrobe_profile/vision_v2_shadow_analysis.dart",
    nodeSource: "functions/prepare_vision_family_identity_input.js",
    input: "trusted parser responses + parity-ready identity qualification + framing/multi-view context",
    output: "BackendFamilyIdentityInput/v1",
    upstream: [
      "VisionFramingAttestor",
      "VisionIdentityQualification",
    ],
    downstream: ["VisionFamilyIdentityResolver"],
    status: "orchestration_ready",
    portableNow: true,
    blockers: [],
  }),
  orchestrationStage({
    id: "PrepareVisionKnowledgeBasePriorInput",
    dartSource: "lib/domain/wardrobe_profile/vision_v2_shadow_analysis.dart",
    nodeSource: "functions/prepare_vision_knowledge_base_prior_input.js",
    input: "parity-ready observation + qualified identity + capability evidence",
    output: "wardrobe_kb_prior_input/v1",
    upstream: [
      "VisionObservationEvidenceProvider",
      "VisionIdentityQualification",
      "WardrobeCapabilityInferenceProvider",
    ],
    downstream: ["WardrobeKnowledgeBasePriorProvider"],
    status: "orchestration_ready",
    portableNow: true,
    blockers: [],
  }),
  orchestrationStage({
    id: "PrepareWardrobeProfileResolverInput",
    dartSource: "lib/domain/wardrobe_profile/vision_v2_shadow_analysis.dart",
    nodeSource: "functions/prepare_wardrobe_profile_resolver_input.js",
    input: "parity-ready observation + identity + capability + kb prior evidence",
    output: "wardrobe_profile_resolver_input/v1",
    upstream: [
      "VisionObservationEvidenceProvider",
      "VisionIdentityQualification",
      "WardrobeCapabilityInferenceProvider",
      "WardrobeKnowledgeBasePriorProvider",
    ],
    downstream: ["WardrobeProfileResolver"],
    status: "orchestration_ready",
    portableNow: true,
    blockers: [],
  }),
  orchestrationStage({
    id: "PrepareQualifiedVisionPersistenceMapperInput",
    dartSource: "lib/domain/wardrobe_profile/qualified_vision_persistence_mapper.dart",
    nodeSource: "functions/prepare_qualified_vision_persistence_mapper_input.js",
    input: "parity-ready observation/identity/family/capability + fixture or trusted mapping context",
    output: "qualified_vision_persistence_mapper_input/v1",
    upstream: [
      "VisionObservationEvidenceProvider",
      "VisionIdentityQualification",
      "VisionFamilyIdentityResolver",
      "WardrobeCapabilityInferenceProvider",
      "WardrobeProfileResolver",
    ],
    downstream: ["QualifiedVisionPersistenceMapper"],
    status: "orchestration_ready",
    portableNow: true,
    blockers: [],
    productionBlockers: [
      "migration_required",
      "production_export_pending",
    ],
  }),
]);

/**
 * Shared generated artifacts are not counted in provider/orchestration totals.
 */
const BACKEND_ARTIFACT_GRAPH = Object.freeze([
  artifact({
    id: "ClothingKnowledgeBasePriorArtifact",
    dartSource: "lib/data/clothing_knowledge_base.dart",
    artifactPath:
      "test/fixtures/backend_qualification/artifacts/clothing_knowledge_base_prior_v1.json",
    artifactManifest:
      "test/fixtures/backend_qualification/backend_clothing_kb_prior_artifact_manifest.json",
    artifactVersion: "clothing-kb-prior-artifact-v1",
    schemaVersion: 1,
    consumers: ["WardrobeKnowledgeBasePriorProvider"],
    status: "artifact_ready",
    portableNow: true,
    blockers: [],
    nodeLoader: "functions/clothing_knowledge_base_prior_loader.js",
    loaderStatus: "artifact_loader_ready",
    loaderManifest:
      "test/fixtures/backend_qualification/backend_clothing_kb_prior_loader_manifest.json",
  }),
]);

const BACKEND_ARTIFACT_STATUSES = Object.freeze([
  "not_started",
  "artifact_ready",
]);

const BACKEND_ARTIFACT_LOADER_STATUSES = Object.freeze([
  "not_started",
  "artifact_loader_ready",
]);

/**
 * Pure contracts are not counted in provider parity-ready totals.
 */
const BACKEND_CONTRACT_STATUSES = Object.freeze([
  "not_started",
  "contract_ready",
  "adapter_ready_not_wired",
  "wired_offline",
  "lifecycle_ready_offline",
  "orchestration_ready_offline",
  "endpoint_ready_offline",
  "repository_ready_offline",
  "production_wiring_ready_unexported",
  "handler_ready_unexported",
  "handler_export_ready",
  "production_adapter_ready_unwired_export",
  "rules_ready_emulator",
  "rules_foundation_pending_baseline",
  "client_write_path_cutover_ready",
  "client_app_check_ready",
  "runtime_ready",
]);

const contract = (definition) => Object.freeze({
  kind: "trusted_contract",
  nodeSource: null,
  productionReady: false,
  ...definition,
  blockers: Object.freeze([...(definition.blockers || [])]),
  productionBlockers: Object.freeze([...(definition.productionBlockers || [])]),
});

const BACKEND_CONTRACT_GRAPH = Object.freeze([
  contract({
    id: "TrustedRevisionContract",
    dartSource: null,
    nodeSource: "functions/wardrobe_qualification_revision_contract.js",
    input: "trusted Storage object metadata + backend-assigned monotonic revisions",
    output: "WardrobeQualificationRevisionContext/v1",
    status: "contract_ready",
    portableNow: true,
    productionReady: false,
    blockers: [
      "migration_required",
      "production_export_pending",
    ],
    productionBlockers: [
      "migration_required",
      "production_export_pending",
      "deployment_pending",
    ],
    contractVersion: "wardrobe-qualification-revision-context-v1",
  }),
  contract({
    id: "TrustedStorageMetadataAdapter",
    dartSource: null,
    nodeSource: "functions/trusted_storage_metadata_adapter.js",
    input: "uid + itemId + sourceStoragePath + Storage metadata client",
    output: "TrustedSourceObjectSnapshot/v1",
    status: "production_adapter_ready_unwired_export",
    portableNow: true,
    productionReady: false,
    blockers: [
      "production_export_pending",
      "deployment_pending",
    ],
    productionBlockers: [
      "production_export_pending",
      "deployment_pending",
    ],
    contractVersion: "trusted-storage-metadata-adapter-v1",
  }),
  contract({
    id: "WardrobeRevisionLifecycleMutationService",
    dartSource: null,
    nodeSource: "functions/wardrobe_revision_lifecycle_mutation_service.js",
    input: "WardrobeRevisionLifecycleMutationRequest/v1 + trusted actor + optional Storage snapshot",
    output: "WardrobeRevisionLifecycleMutationResult/v1",
    status: "lifecycle_ready_offline",
    portableNow: true,
    productionReady: false,
    blockers: [
      "production_export_pending",
      "deployment_pending",
    ],
    productionBlockers: [
      "production_export_pending",
      "deployment_pending",
    ],
    dependsOn: [
      "TrustedRevisionContract",
      "TrustedStorageMetadataAdapter",
    ],
    contractVersion: "wardrobe-revision-lifecycle-mutation-service-v1",
  }),
  contract({
    id: "AsyncFirestoreReadBoundary",
    dartSource: null,
    nodeSource: "functions/wardrobe_admin_firestore_transactional_store.js",
    input: "sync/async plain data or Admin Firestore DocumentSnapshot",
    output: "WardrobeDocumentReadStore/v1: immutable plain map or null",
    status: "runtime_ready",
    portableNow: true,
    productionReady: true,
    blockers: [],
    productionBlockers: [],
    contractVersion: "WardrobeDocumentReadStore/v1",
  }),
  contract({
    id: "LiveModelProvenanceGate",
    dartSource: null,
    nodeSource: "functions/trusted_vision_result_provenance.js",
    input: "TrustedVisionAnalysisClient/v1 result + explicit runtime policy",
    output: "TrustedVisionResultProvenance/v1 validation result",
    status: "runtime_ready",
    portableNow: true,
    productionReady: true,
    blockers: [],
    productionBlockers: [],
    contractVersion: "TrustedVisionResultProvenance/v1",
  }),
  contract({
    id: "WardrobeBackendQualificationOrchestrator",
    dartSource: null,
    nodeSource: "functions/wardrobe_backend_qualification_orchestrator.js",
    input: "parser fixture / trusted stage handoffs + optional trusted mapping context",
    output: "mapper result + resolved profile (offline)",
    status: "orchestration_ready_offline",
    portableNow: true,
    productionReady: false,
    blockers: [
      "production_endpoint_not_exported",
      "deployment_pending",
    ],
    productionBlockers: [
      "production_endpoint_not_exported",
      "deployment_pending",
    ],
    dependsOn: [
      "AsyncFirestoreReadBoundary",
      "LiveModelProvenanceGate",
      "QualifiedVisionPersistenceMapper",
      "TrustedRevisionContract",
    ],
    contractVersion: "wardrobe-backend-qualification-orchestrator-v1",
  }),
  contract({
    id: "TrustedVisionQualificationInput",
    dartSource: null,
    nodeSource: "functions/trusted_vision_qualification_input.js",
    input: "server identity + trusted parser/source/revision attestations",
    output: "immutable TrustedVisionQualificationInput/v1",
    status: "contract_ready",
    portableNow: true,
    productionReady: false,
    productionExport: false,
    blockers: [],
    productionBlockers: ["controlled_live_shadow_smoke_pending"],
    contractVersion: "trusted-vision-qualification-input/v1",
  }),
  contract({
    id: "ServerAnalysisIdentityAuthority",
    dartSource: null,
    nodeSource: "functions/server_analysis_identity.js",
    input: "trusted generation + server attempt + ordered sources",
    output: "ServerAnalysisIdentity/v1",
    status: "contract_ready",
    portableNow: true,
    productionReady: false,
    productionExport: false,
    blockers: [],
    productionBlockers: ["controlled_live_shadow_smoke_pending"],
    contractVersion: "server-analysis-identity/v1",
  }),
  contract({
    id: "TrustedAnalysisKindAuthority",
    dartSource: null,
    nodeSource: "functions/server_analysis_identity.js",
    input: "server policy analysisKind before identity allocation",
    output: "validated initial_analysis or reanalysis identity authority",
    status: "contract_ready",
    portableNow: true,
    productionReady: false,
    productionExport: false,
    blockers: [],
    productionBlockers: ["controlled_live_shadow_smoke_pending"],
    dependsOn: ["ServerAnalysisIdentityAuthority",
      "TrustedVisionQualificationInput"],
    contractVersion: "server-analysis-identity/v1",
  }),
  contract({
    id: "LiveParserRuntimeOrchestrator",
    dartSource: null,
    nodeSource: "functions/live_parser_backend_qualification_orchestrator.js",
    input: "TrustedVisionQualificationInput/v1",
    output: "LiveParserBackendQualificationResult/v1",
    status: "runtime_ready",
    portableNow: true,
    productionReady: false,
    productionExport: false,
    blockers: [],
    productionBlockers: ["controlled_live_shadow_smoke_pending"],
    dependsOn: ["TrustedVisionQualificationInput",
      "ServerAnalysisIdentityAuthority"],
    contractVersion: "live-parser-backend-qualification-orchestrator-v1",
  }),
  contract({
    id: "ControlledShadowActivationPolicy",
    dartSource: null,
    nodeSource: "functions/controlled_shadow_activation_policy.js",
    input: "strict server-injected exact UID/item/action/time policy",
    output: "redacted allow/deny decision + lease binding",
    status: "contract_ready",
    portableNow: true,
    productionReady: false,
    productionExport: true,
    blockers: [],
    productionBlockers: ["manual_policy_configuration_pending"],
    dependsOn: [],
    contractVersion: "ControlledShadowActivationPolicy/v1",
  }),
  contract({
    id: "ControlledShadowConfiguration",
    dartSource: null,
    nodeSource: "functions/controlled_shadow_policy_config.js",
    input: "WARDROBE_SHADOW_POLICY Secret Manager JSON",
    output: "strict lazy redacted controlled shadow policy",
    status: "contract_ready",
    portableNow: true,
    productionReady: false,
    productionExport: true,
    blockers: ["manual_policy_configuration_pending"],
    productionBlockers: ["manual_policy_configuration_pending"],
    dependsOn: ["ControlledShadowActivationPolicy"],
    contractVersion: "ControlledShadowPolicyConfiguration/v1",
  }),
  contract({
    id: "SingleUseShadowLease",
    dartSource: null,
    nodeSource: "functions/single_use_shadow_lease.js",
    input: "server-owned lease + atomic Admin transaction adapter",
    output: "single accepted request or fail-closed rejection",
    status: "runtime_ready",
    portableNow: true,
    productionReady: false,
    productionExport: true,
    blockers: ["manual_lease_creation_pending"],
    productionBlockers: ["manual_lease_creation_pending"],
    dependsOn: ["ControlledShadowActivationPolicy"],
    contractVersion: "SingleUseShadowLease/v1",
  }),
  contract({
    id: "LiveShadowWiring",
    dartSource: null,
    nodeSource: "functions/wardrobe_authority_shadow_runner.js",
    input: "production shadow gates + trusted Admin/Vision dependencies",
    output: "redacted zero-write shadow simulation",
    status: "runtime_ready",
    portableNow: true,
    productionReady: false,
    productionExport: true,
    blockers: [],
    productionBlockers: ["manual_policy_configuration_pending",
      "manual_lease_creation_pending", "disabled_redeploy_pending",
      "controlled_live_shadow_smoke_pending"],
    dependsOn: ["AsyncFirestoreReadBoundary", "LiveModelProvenanceGate",
      "TrustedVisionQualificationInput", "LiveParserRuntimeOrchestrator",
      "ControlledShadowActivationPolicy", "ControlledShadowConfiguration",
      "SingleUseShadowLease"],
    contractVersion: "wardrobe-qualification-authority-shadow-v1",
  }),
  contract({
    id: "OpenAISecretBinding",
    dartSource: null,
    nodeSource: "functions/openai_secret_binding.js",
    input: "Firebase Secret Manager runtime binding",
    output: "strict runtime-only OpenAI credential resolver",
    status: "contract_ready",
    portableNow: true,
    productionReady: false,
    productionExport: true,
    secretName: "OPENAI_API_KEY",
    blockers: ["manual_secret_creation_pending"],
    productionBlockers: ["manual_secret_creation_pending",
      "disabled_redeploy_pending"],
    contractVersion: "OpenAISecretBinding/v1",
  }),
  contract({
    id: "WardrobeRevisionLifecycleEndpoint",
    dartSource: null,
    nodeSource: "functions/wardrobe_revision_lifecycle_endpoint.js",
    input: "WardrobeRevisionLifecycleEndpointRequest/v1 + trusted auth context",
    output: "WardrobeRevisionLifecycleEndpointResult/v1",
    status: "endpoint_ready_offline",
    portableNow: true,
    productionReady: false,
    blockers: [
      "production_export_pending",
      "deployment_pending",
    ],
    productionBlockers: [
      "production_export_pending",
      "deployment_pending",
    ],
    dependsOn: [
      "WardrobeRevisionLifecycleMutationService",
      "TrustedStorageMetadataAdapter",
    ],
    contractVersion: "wardrobe-revision-lifecycle-endpoint-v1",
  }),
  contract({
    id: "WardrobeQualificationAuthorityEndpoint",
    dartSource: null,
    nodeSource: "functions/wardrobe_qualification_authority_endpoint.js",
    input: "WardrobeQualificationAuthorityRequest/v1 + trusted auth context",
    output: "WardrobeQualificationAuthorityResult/v1",
    status: "endpoint_ready_offline",
    portableNow: true,
    productionReady: false,
    blockers: [
      "production_export_pending",
      "migration_required",
      "deployment_pending",
    ],
    productionBlockers: [
      "production_export_pending",
      "migration_required",
      "deployment_pending",
    ],
    dependsOn: [
      "WardrobeBackendQualificationOrchestrator",
      "WardrobeProfilePersistenceRepositoryAdapter",
      "TrustedStorageMetadataAdapter",
      "WardrobeRevisionLifecycleMutationService",
    ],
    contractVersion: "wardrobe-qualification-authority-endpoint-v1",
  }),
  contract({
    id: "WardrobeProfilePersistenceRepositoryAdapter",
    dartSource:
      "lib/domain/wardrobe_profile/wardrobe_profile_persistence_repository.dart",
    nodeSource: "functions/wardrobe_profile_firestore_repository.js",
    input: "mapped envelope + WardrobeQualificationRevisionContext/v1 + TrustedSourceObjectSnapshot/v1",
    output: "WardrobeProfileRepositoryWriteResult/v1",
    status: "wired_offline",
    portableNow: true,
    productionReady: false,
    blockers: [
      "production_export_pending",
      "migration_required",
      "deployment_pending",
    ],
    productionBlockers: [
      "production_export_pending",
      "migration_required",
      "deployment_pending",
    ],
    dependsOn: [
      "TrustedRevisionContract",
      "TrustedStorageMetadataAdapter",
      "WardrobeRevisionLifecycleMutationService",
      "QualifiedVisionPersistenceMapper",
    ],
  }),
  contract({
    id: "SecurityRulesBoundary",
    dartSource: null,
    nodeSource: "functions/wardrobe_firestore_rules_baseline_discovery.js",
    rulesSource: "firestore.rules",
    input: "client Firestore wardrobe create/update/delete",
    output: "backend-owned field denial + owner UX allow",
    status: "rules_ready_emulator",
    portableNow: true,
    productionReady: false,
    discoveryCompleted: true,
    baselineAbsentInRepo: false,
    deployableBaselinePath: "firestore.rules",
    fragmentReferenceOnly: true,
    fragmentSource: "firestore/wardrobe_backend_boundary.rules",
    blockers: [
      "deployment_pending",
    ],
    productionBlockers: [
      "deployment_pending",
    ],
  }),
  contract({
    id: "WardrobeAuthorityProductionDependencies",
    dartSource: null,
    nodeSource: "functions/wardrobe_authority_production_dependencies.js",
    input: "validated production config + injectable Admin/Vision adapters",
    output: "lazy production dependency graph (unexported)",
    status: "production_wiring_ready_unexported",
    portableNow: true,
    productionReady: false,
    productionExport: false,
    blockers: [
      "migration_required",
      "deployment_pending",
    ],
    productionBlockers: [
      "migration_required",
      "deployment_pending",
    ],
    contractVersion: "wardrobe-authority-production-dependencies-v1",
  }),
  contract({
    id: "WardrobeQualificationAuthorityHandler",
    dartSource: null,
    nodeSource: "functions/wardrobe_qualification_authority_handler.js",
    input: "callable data + Firebase runtime context",
    output: "redacted WardrobeQualificationAuthorityResult/v1",
    status: "handler_export_ready",
    defaultMode: "disabled",
    portableNow: true,
    productionReady: false,
    productionExport: true,
    secretBinding: "ready",
    blockers: [
      "manual_deployment_approval",
      "migration_shadow_validation_pending",
    ],
    productionBlockers: [
      "manual_deployment_approval",
      "migration_shadow_validation_pending",
      "deployment_pending",
    ],
    contractVersion: "wardrobe-qualification-authority-handler-v1",
  }),
  contract({
    id: "WardrobeRevisionLifecycleHandler",
    dartSource: null,
    nodeSource: "functions/wardrobe_revision_lifecycle_handler.js",
    input: "callable data + Firebase runtime context",
    output: "redacted lifecycle mutation result",
    status: "handler_export_ready",
    defaultMode: "disabled",
    portableNow: true,
    productionReady: false,
    productionExport: true,
    noOpenAISecretRequired: true,
    blockers: [
      "manual_deployment_approval",
    ],
    productionBlockers: [
      "manual_deployment_approval",
      "deployment_pending",
    ],
    contractVersion: "wardrobe-revision-lifecycle-handler-v1",
  }),
  contract({
    id: "FlutterFirebaseAppCheck",
    dartSource: "lib/Services/firebase_app_check_bootstrap.dart",
    nodeSource: null,
    input: "Firebase.initializeApp completed + platform/build mode",
    output: "App Check activation (SDK attaches token to callables)",
    status: "client_app_check_ready",
    portableNow: true,
    productionReady: false,
    productionExport: false,
    blockers: [],
    productionBlockers: [
      "enforcement_rollout_pending",
    ],
    contractVersion: "flutter-firebase-app-check-v1",
  }),
  contract({
    id: "TrustedVisionProductionAnalysisClient",
    dartSource: null,
    nodeSource: "functions/trusted_vision_production_analysis_client.js",
    input: "server-owned Storage path + media accessor + transport",
    output: "TrustedVisionAnalysisClient/v1 parser DTO",
    status: "production_adapter_ready_unwired_export",
    portableNow: true,
    productionReady: false,
    productionExport: false,
    blockers: [
      "existing_handler_requires_client_image_url",
      "production_export_pending",
      "deployment_pending",
    ],
    productionBlockers: [
      "existing_handler_requires_client_image_url",
      "production_export_pending",
      "deployment_pending",
    ],
    contractVersion: "trusted-vision-production-analysis-client-v1",
  }),
  contract({
    id: "ClientWritePathCutover",
    dartSource: "lib/Services/wardrobe_write_path_cutover.dart",
    nodeSource: null,
    input: "Flutter UX wardrobe create/edit/reanalyze writes",
    output: "lifecycle/authority callable requests (soft-deferred until export)",
    status: "client_write_path_cutover_ready",
    portableNow: true,
    productionReady: false,
    productionExport: false,
    blockers: [
      "production_export_pending",
      "deployment_pending",
    ],
    productionBlockers: [
      "production_export_pending",
      "deployment_pending",
      "migration_required",
    ],
    dependsOn: [
      "WardrobeRevisionLifecycleHandler",
      "WardrobeQualificationAuthorityHandler",
    ],
    contractVersion: "wardrobe-client-write-path-cutover-v1",
  }),
  contract({
    id: "ControlledWriteActivationPolicy",
    dartSource: null,
    nodeSource: "functions/controlled_write_activation_policy.js",
    input: "server-owned exact UID/item/action/window policy secret",
    output: "ControlledWriteActivationPolicy/v1 decision + policy fingerprint",
    status: "contract_ready",
    portableNow: true,
    productionReady: false,
    blockers: ["manual_controlled_write_policy_configuration_pending"],
    productionBlockers: ["manual_controlled_write_policy_configuration_pending"],
    contractVersion: "controlled-write-activation-policy-v1",
  }),
  contract({
    id: "ControlledWriteSingleUseLease",
    dartSource: null,
    nodeSource: "functions/controlled_write_single_use_lease.js",
    input: "policy-bound Admin Firestore lease transaction",
    output: "one global controlled-write winner",
    status: "runtime_ready",
    portableNow: true,
    productionReady: false,
    blockers: ["manual_controlled_write_lease_creation_pending"],
    productionBlockers: ["manual_controlled_write_lease_creation_pending"],
    contractVersion: "controlled-write-single-use-lease-v1",
  }),
  contract({
    id: "ControlledWriteRuntime",
    dartSource: null,
    nodeSource: "functions/wardrobe_qualification_authority_endpoint.js",
    input: "accepted exact policy + consumed lease + trusted live analysis",
    output: "one atomic authority/profile persistence decision",
    status: "runtime_ready_disabled",
    portableNow: true,
    productionReady: false,
    blockers: ["controlled_write_canary_retry_pending"],
    productionBlockers: ["controlled_write_canary_retry_pending",
      "controlled_write_production_activation_approval_pending"],
    contractVersion: "controlled-write-runtime-v1",
  }),
  contract({
    id: "ProductionAuthoritySwitch",
    dartSource: null,
    nodeSource: "functions/wardrobe_authority_callable_exports.js",
    input: "exported callables + mode + cohort + shadow validation",
    output: "production authority switch (disabled; canary retry pending)",
    status: "not_started",
    defaultMode: "disabled",
    portableNow: true,
    productionReady: false,
    productionExport: false,
    blockers: [
      "controlled_write_canary_retry_pending",
      "controlled_write_production_activation_approval_pending",
    ],
    productionBlockers: [
      "controlled_write_canary_retry_pending",
      "controlled_write_production_activation_approval_pending",
    ],
    contractVersion: "production-authority-switch-v1",
  }),
]);

module.exports = {
  BACKEND_ARTIFACT_GRAPH,
  BACKEND_ARTIFACT_LOADER_STATUSES,
  BACKEND_ARTIFACT_STATUSES,
  BACKEND_CONTRACT_GRAPH,
  BACKEND_CONTRACT_STATUSES,
  BACKEND_ORCHESTRATION_GRAPH,
  BACKEND_ORCHESTRATION_STATUSES,
  BACKEND_PROVIDER_GRAPH,
  BACKEND_PROVIDER_STATUSES,
};
