"use strict";

/**
 * Reproducible Phase 5.3B-1C ranking metadata.
 *
 * This file is audit-only. It is never imported by a production entry point.
 * Scores describe migration readiness, not product importance.
 */
const WEIGHTS = Object.freeze({
  authoritativeInput: 20,
  authoritativeOutput: 20,
  noNewOracle: 15,
  noKb: 8,
  noResolver: 8,
  noMapper: 8,
  noOrchestration: 6,
  unlocks: 3,
  authorityBenefit: 3,
  missingUpstream: -12,
  complexity: -5,
  hiddenTransformRisk: -5,
});

const COMPLETED_IDS = Object.freeze([
  "VisionFramingAttestor",
  "VisionPropertyApplicabilityQualifier",
  "VisionVisibilityTrustQualifier",
  "CanonicalObservationConsistencyValidator",
  "VisionNegativeClaimCorroborator",
  "ObservationAbsenceQualifier",
  "VisionIdentityQualification",
  "VisionFamilyIdentityResolver",
  "WardrobeKnowledgeBasePriorProvider",
  "WardrobeProfileResolver",
  "QualifiedVisionPersistenceMapper",
  "WardrobeProfilePersistenceRepositoryAdapter",
]);

const candidate = (value) => Object.freeze({
  ...value,
  upstream: Object.freeze([...value.upstream]),
  downstream: Object.freeze([...value.downstream]),
  existingNodeDependencies: Object.freeze([
    ...value.existingNodeDependencies,
  ]),
});

const MIGRATION_CANDIDATES = Object.freeze([
  candidate({
    id: "VisionFramingAttestor",
    kind: "validator",
    dartSource:
      "lib/domain/wardrobe_profile/vision_framing_attestation.dart",
    input: "parser inputAssessment + subjectAssessment + quality + framingAttestations",
    output: "VisionFramingAttestationReport",
    upstream: [],
    downstream: [
      "VisionPropertyApplicabilityQualifier",
      "VisionNegativeClaimCorroborator",
      "VisionIdentityQualification",
      "VisionFamilyIdentityResolver",
    ],
    existingNodeDependencies: [
      "VisionFramingAttestor",
      "VisionVisibilityTrustQualifier",
    ],
    existingOracle: false,
    needsNewOracle: true,
    needsKb: false,
    needsOrchestrator: true,
    needsResolver: false,
    needsMapper: false,
    productionBlocker: false,
    authoritativeInput: true,
    authoritativeOutput: false,
    missingUpstreamCount: 0,
    complexity: 2,
    hiddenTransformRisk: 1,
    authorityBenefit: 5,
    unlockCount: 4,
    captureBoundary:
      "VisionV2ShadowOrchestrator.analyze: immediately around attest()",
  }),
  candidate({
    id: "VisionPropertyApplicabilityQualifier",
    kind: "qualifier",
    dartSource: "lib/domain/wardrobe_profile/vision_subject_safety.dart",
    input: "raw observations + framing-qualified subject",
    output: "VisionApplicabilityReport",
    upstream: ["VisionFramingAttestor"],
    downstream: ["VisionVisibilityTrustQualifier"],
    existingNodeDependencies: ["VisionFramingAttestor"],
    existingOracle: false,
    needsNewOracle: true,
    needsKb: false,
    needsOrchestrator: true,
    needsResolver: false,
    needsMapper: false,
    productionBlocker: false,
    authoritativeInput: true,
    authoritativeOutput: false,
    missingUpstreamCount: 0,
    complexity: 3,
    hiddenTransformRisk: 1,
    authorityBenefit: 5,
    unlockCount: 1,
  }),
  candidate({
    id: "VisionVisibilityTrustQualifier",
    kind: "qualifier",
    dartSource: "lib/domain/wardrobe_profile/vision_visibility_trust.dart",
    input: "applicability-qualified bundle + view context",
    output: "VisionVisibilityTrustReport",
    upstream: ["VisionPropertyApplicabilityQualifier"],
    downstream: ["VisionNegativeClaimCorroborator"],
    existingNodeDependencies: ["VisionPropertyApplicabilityQualifier"],
    existingOracle: false,
    needsNewOracle: true,
    needsKb: false,
    needsOrchestrator: true,
    needsResolver: false,
    needsMapper: false,
    productionBlocker: false,
    authoritativeInput: true,
    authoritativeOutput: false,
    missingUpstreamCount: 0,
    complexity: 4,
    hiddenTransformRisk: 2,
    authorityBenefit: 5,
    unlockCount: 1,
  }),
  candidate({
    id: "VisionNegativeClaimCorroborator",
    kind: "qualifier",
    dartSource:
      "lib/domain/wardrobe_profile/vision_framing_attestation.dart",
    input: "visibility bundle + framing/subject + multi-view conflict context",
    output: "NegativeClaimCorroborationReport",
    upstream: [
      "VisionFramingAttestor",
      "VisionVisibilityTrustQualifier",
    ],
    downstream: ["ObservationAbsenceQualifier"],
    existingNodeDependencies: [],
    existingOracle: true,
    needsNewOracle: false,
    needsKb: false,
    needsOrchestrator: true,
    needsResolver: false,
    needsMapper: false,
    productionBlocker: false,
    authoritativeInput: true,
    authoritativeOutput: false,
    missingUpstreamCount: 0,
    complexity: 4,
    hiddenTransformRisk: 2,
    authorityBenefit: 5,
    unlockCount: 1,
  }),
  candidate({
    id: "ObservationAbsenceQualifier",
    kind: "qualifier",
    dartSource:
      "lib/domain/wardrobe_profile/observation_absence_qualifier.dart",
    input: "corroboration-qualified bundles",
    output: "ObservationAbsenceQualificationReport",
    upstream: ["VisionNegativeClaimCorroborator"],
    downstream: ["VisionObservationEvidenceProvider"],
    existingNodeDependencies: ["VisionNegativeClaimCorroborator"],
    existingOracle: true,
    needsNewOracle: false,
    needsKb: false,
    needsOrchestrator: true,
    needsResolver: false,
    needsMapper: false,
    productionBlocker: false,
    authoritativeInput: true,
    authoritativeOutput: false,
    missingUpstreamCount: 0,
    complexity: 3,
    hiddenTransformRisk: 1,
    authorityBenefit: 5,
    unlockCount: 1,
  }),
  candidate({
    id: "CanonicalObservationConsistencyValidator",
    kind: "validator",
    dartSource:
      "lib/domain/wardrobe_profile/canonical_observation_consistency_validator.dart",
    input: "raw identity evidence + observation evidence",
    output: "CanonicalConsistencyReport",
    upstream: ["VisionObservationEvidenceProvider"],
    downstream: ["VisionIdentityQualification"],
    existingNodeDependencies: ["VisionObservationEvidenceProvider"],
    existingOracle: false,
    needsNewOracle: true,
    needsKb: false,
    needsOrchestrator: true,
    needsResolver: false,
    needsMapper: false,
    productionBlocker: false,
    authoritativeInput: true,
    authoritativeOutput: false,
    missingUpstreamCount: 0,
    complexity: 5,
    hiddenTransformRisk: 2,
    authorityBenefit: 4,
    unlockCount: 1,
    captureBoundary:
      "VisionV2ShadowOrchestrator.analyze: immediately around validate()",
  }),
  candidate({
    id: "VisionIdentityQualification",
    kind: "private_orchestration_stage",
    dartSource:
      "lib/domain/wardrobe_profile/vision_v2_shadow_analysis.dart",
    input: "identity candidates + consistency + supports + framing validity",
    output: "qualified identity evidence + qualification report",
    upstream: [
      "VisionFramingAttestor",
      "CanonicalObservationConsistencyValidator",
    ],
    downstream: [
      "VisionFamilyIdentityResolver",
      "WardrobeKnowledgeBasePriorProvider",
      "WardrobeProfileResolver",
      "QualifiedVisionPersistenceMapper",
    ],
    existingNodeDependencies: [
      "VisionFramingAttestor",
      "CanonicalObservationConsistencyValidator",
      "VisionObservationEvidenceProvider",
    ],
    existingOracle: true,
    needsNewOracle: false,
    needsKb: false,
    needsOrchestrator: false,
    needsResolver: false,
    needsMapper: false,
    productionBlocker: false,
    authoritativeInput: true,
    authoritativeOutput: false,
    missingUpstreamCount: 0,
    complexity: 5,
    hiddenTransformRisk: 3,
    authorityBenefit: 5,
    unlockCount: 4,
  }),
  candidate({
    id: "VisionFamilyIdentityResolver",
    kind: "resolver",
    dartSource: "lib/domain/wardrobe_profile/vision_family_identity.dart",
    input: "identity candidates + observations + qualified subtype + framing",
    output: "VisionFamilyIdentityReport",
    upstream: [
      "VisionFramingAttestor",
      "VisionIdentityQualification",
    ],
    downstream: ["QualifiedVisionPersistenceMapper"],
    existingNodeDependencies: [
      "VisionFramingAttestor",
      "VisionIdentityQualification",
    ],
    existingOracle: true,
    needsNewOracle: false,
    needsKb: false,
    needsOrchestrator: false,
    needsResolver: false,
    needsMapper: true,
    productionBlocker: false,
    authoritativeInput: true,
    authoritativeOutput: true,
    missingUpstreamCount: 0,
    complexity: 4,
    hiddenTransformRisk: 2,
    authorityBenefit: 4,
    unlockCount: 1,
  }),
  candidate({
    id: "WardrobeKnowledgeBasePriorProvider",
    kind: "provider",
    dartSource:
      "lib/domain/wardrobe_profile/wardrobe_knowledge_base_prior_provider.dart",
    input: "empty vision document + observation/identity/capability evidence",
    output: "knowledge-base prior evidence",
    upstream: [
      "VisionObservationEvidenceProvider",
      "VisionIdentityQualification",
      "WardrobeCapabilityInferenceProvider",
    ],
    downstream: ["WardrobeProfileResolver"],
    existingNodeDependencies: [
      "VisionObservationEvidenceProvider",
      "VisionIdentityQualification",
      "WardrobeCapabilityInferenceProvider",
    ],
    existingOracle: true,
    needsNewOracle: false,
    needsKb: false,
    needsOrchestrator: false,
    needsResolver: true,
    needsMapper: false,
    productionBlocker: false,
    authoritativeInput: true,
    authoritativeOutput: true,
    missingUpstreamCount: 0,
    complexity: 4,
    hiddenTransformRisk: 2,
    authorityBenefit: 3,
    unlockCount: 1,
  }),
  candidate({
    id: "WardrobeProfileResolver",
    kind: "final_resolver",
    dartSource:
      "lib/domain/wardrobe_profile/wardrobe_profile_resolver.dart",
    input: "itemId + observation/identity/capability/kb prior evidence",
    output: "ResolvedWardrobeItemProfile",
    upstream: [
      "VisionObservationEvidenceProvider",
      "VisionIdentityQualification",
      "WardrobeCapabilityInferenceProvider",
      "WardrobeKnowledgeBasePriorProvider",
    ],
    downstream: [],
    existingNodeDependencies: [
      "VisionObservationEvidenceProvider",
      "VisionIdentityQualification",
      "WardrobeCapabilityInferenceProvider",
      "WardrobeKnowledgeBasePriorProvider",
    ],
    existingOracle: true,
    needsNewOracle: false,
    needsKb: false,
    needsOrchestrator: false,
    needsResolver: true,
    needsMapper: false,
    productionBlocker: true,
    authoritativeInput: true,
    authoritativeOutput: true,
    missingUpstreamCount: 0,
    complexity: 5,
    hiddenTransformRisk: 2,
    authorityBenefit: 5,
    unlockCount: 1,
  }),
  candidate({
    id: "QualifiedVisionPersistenceMapper",
    kind: "mapper",
    dartSource:
      "lib/domain/wardrobe_profile/qualified_vision_persistence_mapper.dart",
    input: "qualified analysis + persistence context",
    output: "persistence mapping result",
    upstream: [
      "VisionObservationEvidenceProvider",
      "VisionIdentityQualification",
      "VisionFamilyIdentityResolver",
      "WardrobeCapabilityInferenceProvider",
      "WardrobeProfileResolver",
    ],
    downstream: [],
    existingNodeDependencies: [
      "VisionObservationEvidenceProvider",
      "VisionIdentityQualification",
      "VisionFamilyIdentityResolver",
      "WardrobeCapabilityInferenceProvider",
      "WardrobeProfileResolver",
    ],
    existingOracle: true,
    needsNewOracle: false,
    needsKb: false,
    needsOrchestrator: false,
    needsResolver: false,
    needsMapper: true,
    productionBlocker: true,
    authoritativeInput: false,
    authoritativeOutput: false,
    missingUpstreamCount: 0,
    complexity: 5,
    hiddenTransformRisk: 4,
    authorityBenefit: 5,
    unlockCount: 0,
  }),
  candidate({
    id: "WardrobeProfilePersistenceRepositoryAdapter",
    kind: "repository_adapter",
    dartSource:
      "lib/domain/wardrobe_profile/wardrobe_profile_persistence_repository.dart",
    input: "mapped envelope + trusted revision context",
    output: "WardrobeProfileWriteResult",
    upstream: [
      "QualifiedVisionPersistenceMapper",
      "TrustedRevisionContract",
    ],
    downstream: [],
    existingNodeDependencies: [
      "QualifiedVisionPersistenceMapper",
      "TrustedRevisionContract",
    ],
    existingOracle: false,
    needsNewOracle: false,
    needsKb: false,
    needsOrchestrator: true,
    needsResolver: false,
    needsMapper: false,
    productionBlocker: true,
    authoritativeInput: true,
    authoritativeOutput: true,
    missingUpstreamCount: 0,
    complexity: 4,
    hiddenTransformRisk: 3,
    authorityBenefit: 5,
    unlockCount: 1,
  }),
]);

function scoreCandidate(item) {
  return (item.authoritativeInput ? WEIGHTS.authoritativeInput : 0) +
    (item.authoritativeOutput ? WEIGHTS.authoritativeOutput : 0) +
    (!item.needsNewOracle ? WEIGHTS.noNewOracle : 0) +
    (!item.needsKb ? WEIGHTS.noKb : 0) +
    (!item.needsResolver ? WEIGHTS.noResolver : 0) +
    (!item.needsMapper ? WEIGHTS.noMapper : 0) +
    (!item.needsOrchestrator ? WEIGHTS.noOrchestration : 0) +
    item.unlockCount * WEIGHTS.unlocks +
    item.authorityBenefit * WEIGHTS.authorityBenefit +
    item.missingUpstreamCount * WEIGHTS.missingUpstream +
    item.complexity * WEIGHTS.complexity +
    item.hiddenTransformRisk * WEIGHTS.hiddenTransformRisk -
    (item.productionBlocker ? 20 : 0);
}

function rankCandidates() {
  return MIGRATION_CANDIDATES
    .filter((item) => !COMPLETED_IDS.includes(item.id))
    .map((item) => ({
    ...item,
    score: scoreCandidate(item),
  })).sort((left, right) =>
    right.score - left.score || left.id.localeCompare(right.id));
}

module.exports = {
  COMPLETED_IDS,
  MIGRATION_CANDIDATES,
  WEIGHTS,
  rankCandidates,
  scoreCandidate,
};
