"use strict";
const test=require("node:test"),assert=require("node:assert/strict");
const v2=require("./wardrobe_ontology_v2"); const analyzer=require("./wardrobe_analyzer_v2_contract");
function item(type){return {ontologyVersion:"2.0.0",taxonomyVersion:"2.0.0",kbVersion:"2.0.0",...v2.enrichIdentity(type),colorProfile:{primary:{family:"white",hex:"#ffffff",proportion:.96},secondary:null,accents:[{family:"black",hex:"#000000",proportion:.04}],metalTone:"none",hardwareTone:"none"},formality:4,styles:[],occasionFit:[],seasons:[],warmth:3,attributes:{},setMembership:null,fieldSources:{canonicalType:"visual_ai"},fieldConfidence:{canonicalType:.98},userOverrideFields:[]};}
test("taxonomy is complete and separates body slot from layer",()=>{assert.equal(v2.artifact.items.length,170);assert.deepEqual(v2.enrichIdentity("dress").bodySlots,["full_body"]);assert.equal(v2.enrichIdentity("dress").layerPosition,"outer");assert.deepEqual(v2.enrichIdentity("earrings").bodySlots,["ears"]);assert.equal(v2.enrichIdentity("earrings").layerPosition,"not_applicable");assert.equal(v2.enrichIdentity("thermal_underwear_bottom").layerPosition,"skin_base");});
test("generic trousers parent is safer than an unsupported sibling",()=>{const parent=v2.canonicalDefinition("trousers");assert.equal(parent.canonicalFamily,"bottom");assert.equal(parent.uiProjection.mainCategory,"oblecenie");assert.equal(parent.warmthRange.typical,4);for(const child of ["corduroy_pants","linen_pants","suit_trousers","wide_leg_pants","sweatpants"])assert.equal(v2.canonicalDefinition(child).parentType,"trousers");assert.equal(v2.enrichIdentity("trousers").layerPosition,"outer");assert.deepEqual(v2.enrichIdentity("trousers").bodySlots,["lower_body"]);});
test("parent beats fabricated sibling and shoulder bag is distinct",()=>{assert.equal(v2.resolveCanonicalAlias("earrings"),"earrings");assert.equal(v2.resolveCanonicalAlias("shoulder purse"),"shoulder_bag");assert.notEqual(v2.resolveCanonicalAlias("shoulder purse"),"crossbody_bag");});
test("conservative multiplicity",()=>{for(const t of ["watch","belt","necklace","handbag"])assert.equal(v2.enrichIdentity(t).multiplicity.maxPerGroup,1);assert.equal(v2.enrichIdentity("ring").multiplicity.stackable,true);});
test("family-specific attributes stay namespaced",()=>{assert.deepEqual(v2.canonicalDefinition("watch").allowedAttributes,["accessory.watchStyle","accessory.caseSizeClass","accessory.strapAppearance"]);assert.deepEqual(v2.canonicalDefinition("belt").allowedAttributes,["accessory.widthClass","accessory.buckleTone"]);assert.ok(v2.canonicalDefinition("shoulder_bag").allowedAttributes.includes("accessory.hardwareTone"));});
test("semantic accent is not secondary",()=>{const x=item("t_shirt");assert.equal(v2.validateWardrobeItemV2(x).ok,true);assert.equal(x.colorProfile.secondary,null);assert.equal(x.colorProfile.accents[0].family,"black");});
test("wardrobe V2 rejects warmth outside the canonical type range",()=>{const x=item("chelsea_boots");x.warmth=4;assert.equal(v2.validateWardrobeItemV2(x).ok,true);x.warmth=3;assert.ok(v2.validateWardrobeItemV2(x).errors.includes("warmth.out_of_type_range"));});
test("user overrides survive analyzer reanalysis",()=>{const x=item("t_shirt");x.userOverrideFields=["canonicalType"];x.fieldSources.canonicalType="user_correction";const y=v2.applyAnalyzerResult(x,{identity:{canonicalType:"dress"},observed:{},inferred:{},evidence:{fieldConfidence:{}}});assert.equal(y.canonicalType,"t_shirt");});
test("set membership does not alter composition",()=>{const x=item("blazer");x.setMembership={setId:"set-1",setType:"suit"};assert.equal(v2.validateWardrobeItemV2(x).ok,true);assert.equal(Object.hasOwn(x,"compositionRole"),false);});
test("Gemini transport projection is flat and omits canonical taxonomy enum",()=>{const schema=analyzer.buildGeminiResponseSchema();assert.equal(schema.properties.canonicalType.enum,undefined);assert.equal(schema.properties.identity,undefined);assert.equal(schema.properties.contractVersion.enum[0],"wardrobe-analyzer-v2");});
