"use strict";

/** Named/versioned Phase 7 policy constants (report in completion). */
const USER_TRACKING_OPTION_COUNT = 2;
const LOW_STOCK_TRACKING_OPTION_COUNT = 0;
const USER_LOW_STOCK_MONITORING_OPTION_COUNT = 0;
const PARTNER_POLLING_COUNT = 0;

const LOW_STOCK_QUANTITY_POLICY_V1 = Object.freeze({
  name: "LOW_STOCK_QUANTITY_POLICY_V1",
  maxInclusiveQuantity: 3,
});

const WISHLIST_REFRESH_MAX_ITEMS_V1 = 100;
const WISHLIST_CHANGESET_MAX_VARIANTS_V1 = 500;
const WISHLIST_SUBSCRIBER_PAGE_SIZE_V1 = 500;
const WISHLIST_VARIANT_CHUNK_SIZE_V1 = 100;
const WISHLIST_LAST_EVENT_IDS_CAP_V1 = 20;
const WISHLIST_EVENT_RETENTION_DAYS_V1 = 90;
const WISHLIST_EVENT_RETENTION_MS_V1 =
  WISHLIST_EVENT_RETENTION_DAYS_V1 * 24 * 60 * 60 * 1000;
const WISHLIST_REFRESH_LEASE_MS_V1 = 30 * 1000;
const WISHLIST_PUSH_GROUP_DETAIL_MAX_V1 = 5;
const WISHLIST_PUSH_GROUP_SUMMARY_THRESHOLD_V1 = 6;

const EVENT_TYPES = Object.freeze({
  PRICE_TARGET_SATISFIED: "PRICE_TARGET_SATISFIED",
  PRICE_TARGET_UNSATISFIED: "PRICE_TARGET_UNSATISFIED",
  SIZE_AVAILABLE: "SIZE_AVAILABLE",
  SIZE_UNAVAILABLE: "SIZE_UNAVAILABLE",
  LOW_STOCK_ENTERED: "LOW_STOCK_ENTERED",
});

const CHANGESET_SOURCES = Object.freeze({
  CATALOG_SYNC: "CATALOG_SYNC",
  MANUAL_REFRESH: "MANUAL_REFRESH",
  VISIT_STORE_REVALIDATE: "VISIT_STORE_REVALIDATE",
  TEST_INJECT: "TEST_INJECT",
});

module.exports = {
  CHANGESET_SOURCES,
  EVENT_TYPES,
  LOW_STOCK_QUANTITY_POLICY_V1,
  LOW_STOCK_TRACKING_OPTION_COUNT,
  PARTNER_POLLING_COUNT,
  USER_LOW_STOCK_MONITORING_OPTION_COUNT,
  USER_TRACKING_OPTION_COUNT,
  WISHLIST_CHANGESET_MAX_VARIANTS_V1,
  WISHLIST_EVENT_RETENTION_DAYS_V1,
  WISHLIST_EVENT_RETENTION_MS_V1,
  WISHLIST_LAST_EVENT_IDS_CAP_V1,
  WISHLIST_PUSH_GROUP_DETAIL_MAX_V1,
  WISHLIST_PUSH_GROUP_SUMMARY_THRESHOLD_V1,
  WISHLIST_REFRESH_LEASE_MS_V1,
  WISHLIST_REFRESH_MAX_ITEMS_V1,
  WISHLIST_SUBSCRIBER_PAGE_SIZE_V1,
  WISHLIST_VARIANT_CHUNK_SIZE_V1,
};
