/// Compatibility rules for Home `daily_outfits` vs saved style taste.
///
/// Preference invalidation applies to auto-generated recommendations only.
/// Pinned / manual / swapped outfits keep user intent.
abstract final class HomeTasteCachePolicy {
  static bool isUserPinned({
    required bool userModified,
    required String persistSource,
  }) {
    return userModified || persistSource == 'manual_new_outfit';
  }

  /// Legacy auto-generated docs without a fingerprint cannot prove taste
  /// compatibility and must be treated as stale.
  static bool isAutoGeneratedTasteIncompatible({
    required bool userPinned,
    required String cachedFingerprint,
    required String currentFingerprint,
  }) {
    if (userPinned) return false;
    if (cachedFingerprint.isEmpty) return true;
    return cachedFingerprint != currentFingerprint;
  }
}
